# FROM ubuntu:19.10
FROM tensorflow/tensorflow:2.1.0-py3

LABEL Gerald Weber "e0125536@student.tuwien.ac.at"

# RUN apt-get update -y && \
#     apt-get install -y python3 python3-pip

# We copy just the requirements.txt first to leverage Docker cache
COPY ./super-resolution /super-resolution

WORKDIR /super-resolution

# Update pip for tensorflow2
# RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
## RUN pip3 install --upgrade tensorflow

ENTRYPOINT [ "python3" ]
# run flask app
CMD [ "app.py" ]